rom_config: '../../../extract/jp/config.yaml'
build_path: '../../../build/jp'
delinks_path: '../../../build/jp/delinks'
main_module:
  name: main
  object: '../../../build/jp/build/arm9.bin'
  hash: acf92b3fd9e0a608
  delinks: delinks.txt
  symbols: symbols.txt
  relocations: relocs.txt
autoloads:
- kind: Itcm
  name: itcm
  object: '../../../build/jp/build/itcm.bin'
  hash: '16603e941c0a660a'
  delinks: itcm/delinks.txt
  symbols: itcm/symbols.txt
  relocations: itcm/relocs.txt
- kind: Dtcm
  name: dtcm
  object: '../../../build/jp/build/dtcm.bin'
  hash: '08a0716795baead0'
  delinks: dtcm/delinks.txt
  symbols: dtcm/symbols.txt
  relocations: dtcm/relocs.txt
overlays: []
